### ISSUE TITLE
CS Script Tools Extension is disabled. No compatible CS-Script version found (min v3.4.2.0)

### ISSUE THREAD

**Issue by PeterDrazki** [oleg-shilo/cs-script.net-framework#5]
Hello, I'm using CS Script Tools Extension for Visual Studio 2017-2019. I need CS-Script for .NET framework 4.5 so I installed cs-script v.3.30.5.2 by using Configuration console. It was working until I launched Visual Studio updates (now I have Visual Studio 2019 with .NET framework 4.8.04084) After this in CS Script Tools Extension appears a message: "CS Script Tools Extension is disabled. No compatible CS-Script version found (min v3.4.2.0)". I tried to reinstall cs-script or CS Script Tools Extension or even Visual Studio but still I have the same message. I tried different ways of installation: 
with using Chocolatey or with Configuration Console. I also tried with clear OS, so I created a virtual machine and I installed Visual Studio 2019 (.NET framework 4.8.04084), CS Script Tools Extension, and CS-Script. In the virtual machine is working. But I can't fix the problem on the host PC. Can you help me ?

**Comment by PeterDrazki** [comment]
I solved the problem, the wrong "Engine Script Path" was the cause. I figured out that the path is stored in the CSSCRIPT_DIR variable in Windows Environment Variables. I changed it to the correct one and it started working.

**Comment by oleg-shilo** [comment]
Great, glad you managed to solve it.
