### ISSUE TITLE
hello_auto sample: Cannot find entry point

### ISSUE THREAD

**Issue by megakraken** [oleg-shilo/cs-script.net-framework#8]
Hello,

When trying to run the `hello_auto.cs` script with `cscs /ac samples\hello_auto.cs` I get the following error message:

```
Error: Specified file could not be executed.

System.ApplicationException: Cannot find entry point. Make sure script file contains method: 'public static Main(...)'
   at csscript.RemoteExecutor.InvokeStaticMain(Assembly compiledAssembly, String[] scriptArgs)
   at csscript.CSExecutor.ExecuteImpl()
```
I figured the `/ac` option should do the trick, what am I doing wrong?

For reference, the script looks like this:
```
using System;
using System.Windows.Forms;

void Main()
{	
    Console.WriteLine( "Hello World!" ); 
    MessageBox.Show( "Hello World!"); 
}

```

**Comment by oleg-shilo** [comment]
It is a defect. The auto-class generation algorithm is missing `static` modifier for the method.

I will do a quick fix but until it is available you can use lowercase `main` as a workaround:

```
using System;
using System.Windows.Forms;

void main()
{	
    Console.WriteLine( "Hello World!" ); 
    MessageBox.Show( "Hello World!"); 
}
```

**Comment by oleg-shilo** [comment]
Done. You can download the release from here:
https://github.com/oleg-shilo/cs-script.net-framework/releases/tag/v3.30.7.0

**Comment by megakraken** [comment]
Great, thanks alot!
